gold_set = [
    {"question": "What is the prompt written?", "expected_function": "build_prompt", "expected_file": "prompt.py"},
    {"question": "What is the ranking strategy used?", "expected_function": "reciprocal_rank_fusion", "expected_file": "ranking.py"},
    {"question": "How are embeddings done?", "expected_function": "encodings", "expected_file": "embedder.py"},
    {"question": "Where is the embeddings logic?", "expected_function": "encodings", "expected_file": "embedder.py"},
    {"question": "What is the file chunking logic?", "expected_function": "walk_tree", "expected_file": "read_repo.py"},
    {"question": "How does vector search work?", "expected_function": "vector_search", "expected_file": "search_query.py"},
    {"question": "How does keyword search work?", "expected_function": "keyword_search", "expected_file": "search_query.py"},
    {"question": "How are Python files found in the repo?", "expected_function": "list_python_files", "expected_file": "read_repo.py"},
    {"question": "How is a file's content read?", "expected_function": "read_file", "expected_file": "read_repo.py"},
    {"question": "How is data inserted into the vector database?", "expected_function": "insert_embeddings", "expected_file": "seed_data.py"},
    {"question": "Where is the final answer generated by asking the LLM?", "expected_function": "ask_gemini", "expected_file": "ask.py"},
    {"question": "How do you avoid duplicate rows when re-running data insertion?", "expected_function": "insert_embeddings", "expected_file": "seed_data.py"},
    {"question": "What happens if inserting a chunk fails?", "expected_function": "insert_embeddings", "expected_file": "seed_data.py"},
    {"question": "How are two different search results combined into one ranking?", "expected_function": "reciprocal_rank_fusion", "expected_file": "ranking.py"},
    {"question": "How is user login handled?", "expected_function": None, "expected_file": None},  # trick question — nothing should match
    {"question": "What happens when a table already exists before seeding?", "expected_function": "keyword_search", "expected_file": "keyword_search.py"},
]